
name = "MollikkaStuffMonospaceZolaTheme"
description = "Monospace Zola theme for mollikka.net"
license = "MIT"
homepage = "https://github.com/mollikka/MollikkaStuffMonospaceZolaTheme"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

themes = [
    {name = "themeDefault", color_light="#25533b", color_dark="#232323", favicon="/favicon-themeGreen.ico"},
    {name = "themeRed",     color_light="#940a4f", color_dark="#1e1e28", favicon="/favicon-themeRed.ico"},
    {name = "themeGreen",   color_light="#25533b", color_dark="#232323", favicon="/favicon-themeGreen.ico"},
    {name = "themeBlue",    color_light="#2163a1", color_dark="#281e24", favicon="/favicon-themeBlue.ico"},
]

# The theme author info: you!
[author]
name = "Lauri Tervonen"
homepage = "https://www.mollikka.net"

